[package]
name = "nanachi"
version = "0.1.0"
authors = ["carrotflakes <carrotflakes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"

[dev-dependencies]
rand_pcg = "0.2"
rand_core = "0.5"
